stages:
  data_ingestion:
    cmd: python -m src.data_ingestion
    deps:
    - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
     - data/raw

  data_preprocessing:
    cmd: python -m src.data_preprocessing
    deps:
    - src/data_preprocessing.py
    - data/raw
    # params:
    #   -data_ingestion.test_size
    outs:
     - data/interim

  feature_engineering:
    cmd: python -m src.feature_engineering
    deps:
    - src/feature_engineering.py
    - data/interim
    params:
      - feature_engineering.max_features
    outs:
     - data/processed

  model_building:
    cmd: python -m src.model_building
    deps:
    - src/model_building.py
    - data/processed
    params:
      - model_building.n_estimators
      - model_building.random_state
    outs:
     - models/model.pkl

  model_evaluation:
    cmd: python -m src.model_evaluation
    deps:
    - src/model_evaluation.py
    - models/model.pkl
    # params:
    #   -data_ingestion.test_size
    outs:
     - reports/metrics.json
    